// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(require.resolve('./apply.js'))
  await test.load(require.resolve('./autoack.js'))
  await test.load(require.resolve('./basic.js'))
  await test.load(require.resolve('./core.js'))
  await test.load(require.resolve('./dags.js'))
  await test.load(require.resolve('./encryption.js'))
  await test.load(require.resolve('./fast-forward.js'))
  await test.load(require.resolve('./fork.js'))
  await test.load(require.resolve('./linearizer.js'))
  await test.load(require.resolve('./messages.js'))
  await test.load(require.resolve('./node-buffer.js'))
  await test.load(require.resolve('./optimistic.js'))
  await test.load(require.resolve('./repair.js'))
  await test.load(require.resolve('./snapshots.js'))
  await test.load(require.resolve('./suspend.js'))
  await test.load(require.resolve('./timer.js'))
  await test.load(require.resolve('./topolist.js'))
  await test.load(require.resolve('./trace.js'))
  await test.load(require.resolve('./updates.js'))

  test.resume()
}
