// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./anchors.js')
  await import('./apply.js')
  await import('./autoack.js')
  await import('./basic.js')
  await import('./core.js')
  await import('./dags.js')
  await import('./encryption.js')
  await import('./fast-forward.js')
  await import('./fork.js')
  await import('./linearizer.js')
  await import('./messages.js')
  await import('./node-buffer.js')
  await import('./optimistic.js')
  await import('./snapshots.js')
  await import('./suspend.js')
  await import('./timer.js')
  await import('./topolist.js')
  await import('./trace.js')
  await import('./updates.js')
  await import('./values.js')

  test.resume()
}
