// This runner is auto-generated by Brittle

await runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(import.meta.resolve('./apply.js'))
  await test.load(import.meta.resolve('./autoack.js'))
  await test.load(import.meta.resolve('./basic.js'))
  await test.load(import.meta.resolve('./core.js'))
  await test.load(import.meta.resolve('./dags.js'))
  await test.load(import.meta.resolve('./encryption.js'))
  await test.load(import.meta.resolve('./fast-forward.js'))
  await test.load(import.meta.resolve('./fork.js'))
  await test.load(import.meta.resolve('./linearizer.js'))
  await test.load(import.meta.resolve('./messages.js'))
  await test.load(import.meta.resolve('./node-buffer.js'))
  await test.load(import.meta.resolve('./optimistic.js'))
  await test.load(import.meta.resolve('./repair.js'))
  await test.load(import.meta.resolve('./snapshots.js'))
  await test.load(import.meta.resolve('./suspend.js'))
  await test.load(import.meta.resolve('./timer.js'))
  await test.load(import.meta.resolve('./topolist.js'))
  await test.load(import.meta.resolve('./trace.js'))
  await test.load(import.meta.resolve('./updates.js'))

  test.resume()
}
