# ci for autobase-next
name: ci
on:
  push:
    branches:
      - all
  pull_request:
    branches:
      - all
  workflow_dispatch:


env:
  BRITTLE_TIMEOUT: 60000
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        node-version: [lts/*]
        os: [[self-hosted, Linux], [self-hosted, macOS]]
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.ref }}
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: run tests
        run: npm test
