name: Test with Bare

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64

          - os: macos-latest
            platform: darwin
            arch: x64

          - os: windows-latest
            platform: win32
            arch: x64

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: holepunchto/actions/checkout@v1
      - uses: holepunchto/actions/setup-node@v1
      - uses: holepunchto/actions/setup-bare@v1
      - run: npm install --ignore-scripts --foreground-scripts

      - name: Run tests
        run: npm run test:bare
